local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 25.0
  publish_frequency: 15.0
  static_map: true
  rolling_window: true
  width: 2.5
  height: 2.5
  resolution: 0.25
  transform_tolerance: 0.5
  
  plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
